apiVersion: v1
kind: Secret
metadata:
    name: cnpg-backup-s3-credentials
    namespace: monitoring
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:g6hd7ysaLuveAH32lp/tDgSKOSg=,iv:6AvYC05a1tEH8IIhcAGIXmAmLPMtKpbNiit4EHrL50g=,tag:Qf7vub8m+R3MaV0IPlUtiw==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Sv0Uokd6unzB5UsPDGUc/UQTxtRHdE0QhuKAOh2QfBkx8b6Aqos3gA==,iv:jYSf61dbfy4s5bhy6vIUboXAsnLmylaNneDWyh6MBeg=,tag:tMdidau8JPMtLTtExHZ1VA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNmpLbnFTTjZoT3BNVTl2
            OGkvcGo2WmFZTmRCc0FwMGM4ZW5Ha0d3bDI4ClcrSjZVdlVYM1ZZcDlNdTdtZEd2
            ODlHWk1HZTRNSlYrTzJHRFlQRytKcHcKLS0tIGd3SDV0dWcwUXRHT0Q3MCtVclRG
            WDlVNUN1YXFXTSt2OHNHdXJiM1RPYkUKe5t40dA/cNTn27Y4335YytX+uPAZbPRH
            pEr+wNOmfFsbobJDV9UVbxmJKJMFnSGBw8qEr13GzSlz44nnZsFkuA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l8urdgwakvjweqwxuzma2k3lnz0rym2juyjn9uls330keufsqc7s65c5j5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T07:53:23Z"
    mac: ENC[AES256_GCM,data:TEbdksFoV6Efzbi6/gIRyIjANeJQkqMoKATV2lKFSLA5kTso6zgZvK+bA8rNrpq8oMrodpiR8Hzs0o0FmBetxKXfiYqfc0IyM/QrZj2KaSV+HKIK2bzJ+jIsiCXa6BBH+3Q6gSzx+UjwzjWsRhAhkWkwHbOVvAdMhRLk4U26AUg=,iv:446D3z8pEDodqiciaShEjbaxmAbNqxPkqcKejciQN54=,tag:U4fkjypaYT1B0L3CDi0mMA==,type:str]
    version: 3.13.3
