apiVersion: v1
kind: Secret
metadata:
    name: cnpg-backup-s3-credentials
    namespace: monitoring
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:E5roQw2ElQZ63+0tklwQ4U/s5RE=,iv:a+mz9Hu1spaTshZNW0FLUDKmy6/eyWjlGHC9KHLQWlY=,tag:EUz/dA0G/rZm2va9SmNo8Q==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:u4LTzrKGEkcar48qc9C4gA3CHXfwPIoXlF/fyTBQSMpn8GMwPtx6VA==,iv:hpJHweeQ5ktMqgPcR3F76AfBZKkf2h7cVEnM9ZSjcwQ=,tag:e8Un8JWTpHrNkmRAFQA/TQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrRHgxMzMyOU11UTFQMDdy
            UGczQWt1S0ZVNGNPSWtMSCtVTE9qdWdXSzEwCjRxektmWm1kdGM4Um1rSnJ2bXVa
            TEhDZUttaExNYmhBVjFVQkNiZ25pelUKLS0tIGg1aVV4aEpiUjlMbzNUWjIwNTNv
            WFRUYllnL3FUQzVTZFNMa0h6c1dqd3cKIVNs3RwtvQvk0Pt55Bak8zoLOxjGiQh4
            kI0fW4lSFH/h+LCUzogJp3i0PIyxHiO0eutqXA61ilzDK3MwG2pfMQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l8urdgwakvjweqwxuzma2k3lnz0rym2juyjn9uls330keufsqc7s65c5j5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T07:49:08Z"
    mac: ENC[AES256_GCM,data:pooMFtJUz1ITbdVaKekaOXIqfATUvS0hYEhNhzeU9FMa0Wn4PsBTtyFnKr9q+3ZvlfY6o8sfQNMZ6q1lAu4VGVuVTGTv6oo9lPqm3B0DWHh4psMvxa13+XO9XfGgSYCscGJ64BKknD2UWhoLlOZfHe1/aOrlKUspyaRAQ2OjmB8=,iv:4JQ/4pYqUnk8/rTcZ67rA0RmRQFrp5jlFwT2nR8lXLY=,tag:83e7WVQsnaFn8s3ZLAZSsg==,type:str]
    version: 3.13.3
