apiVersion: v1
kind: Secret
metadata:
    name: cnpg-backup-s3-credentials
    namespace: immich
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:uOsdOakZfrk9Q9DjLxM/OCUQqgs=,iv:G9m926biDj+C7UKbE8ASTorWFqq6GX3gA/KX5aUi46c=,tag:KW7DQLp4o/KdZCW0/Ebb8Q==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:fUG8X5HMEIW+gU7WS6h4NZ7viq/wSGdMfZZQgmSGwnI/k6HE+oSTkg==,iv:yDH8huFlL+EvWjsUY6+2yu+kZrSzVfKYveLbR7y9neI=,tag:3lZgspjbUYCJM72GiYdnUw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQVZOUFhqa1lYOWpaZkJY
            cXV3ZWUzTkE1Tnh6eWVaVjZvZzhEcnd1djE0CkxVTjVlMHoveDQ2VnFZeEtrMDZ2
            UXkzRTc0aHNTMHpKVU5IQWNZaEpJUFEKLS0tIFluSGdFTW4va3ZmbzZwbmt4WHpw
            VWNLMEFjSFlWK3hJYTFqN29YZ0R6L2sKGfZkGMuZcgkx7mZblZkdo4VTnZ+4EvtD
            PEeuMhkmVZCrX30rcW36E49On5NUfPgyFFmW/MnR4uoP7dWgEA18Kg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l8urdgwakvjweqwxuzma2k3lnz0rym2juyjn9uls330keufsqc7s65c5j5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T06:10:40Z"
    mac: ENC[AES256_GCM,data:eYvGuxWXq2+yLuXMbDHlibUIQjipZ5nEa3TiNR7s+4qXJPOSBU0rA7/E9c1L9CN6N710woafgF7m15QyJff7gf9Sl143/33vFF0vZb8QWPtxMulwGr+POGPCKxrmDfoOqUfqW6Zg1j7UVANoXPDcg21IZtIR1IRGEYU2aoTcrRM=,iv:ys+skye+AtpSmuV9km4ntEz43kO2Abm5XD6wuu16ETA=,tag:ADsv108Ea/BiD5r2w8Bttw==,type:str]
    version: 3.13.3
