apiVersion: v1
kind: Secret
metadata:
    name: cnpg-backup-s3-credentials
    namespace: immich
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:s3baScw+tXcz3XgKF2sAS8+mGJw=,iv:CMhH98xnyAWXklgcUTc2tIZ0mcJ8Kr3IS0fYNwtpNoQ=,tag:rlFNtVTPsqfYSb6KLYDUuw==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:gOQtAZI82UZELCwQt8NJnBCND7Sa2TXA/PoqlD6nGVEO4GRSqP61Wg==,iv:wjGOBZq7cX3WzWywu62N2pNNJG6wGoMC/3DJRuafbVo=,tag:8IsOtWyq74SDkKj90Sd1GQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVV3RueVQrLzh0cHJ0ckZu
            SHh3eStadHBOWldlMmNTMHZBcWEvWVRQUGdnClFlUHo4N2NFdFdBSncvaStsOGlK
            Z0ViSm16a3liYlJoRU85bncxWFN6ckUKLS0tIGlLa2FKaG05dWpGcVEyQ3Z1ZHRl
            NVRlOGY3aGt6a3lHOTJQaUlUWmcrLzgKQ4R7nWmQO1W32twXgb3CkiW/v46PvM3v
            +zB+ctlly8oXA6RIJrBH4lOPyLoEl6xKJ2fXOj770AN2lQ6UwSXMmw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l8urdgwakvjweqwxuzma2k3lnz0rym2juyjn9uls330keufsqc7s65c5j5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T07:48:53Z"
    mac: ENC[AES256_GCM,data:TzDclujFLyeHZo1CRwR8JMn4anDxAW7uH24hGjl+m/F9Bq//znpPYqimbhaunRdFY0o49HnAtc1N/3BdNBcqmRkfoZVYKWX6axmBW/aEKa14pXtfGNwS8nsgOQrFd1v4ssbcFSmViJ8RhA4fDoYSoU2KPweD+qlMCphRVXZUEg4=,iv:q7qqkvIjQ9AWnU9qWn4hMzDDN5gRZ51xE+91tCNDUdU=,tag:AXKGlJnxO5gkXULYtNEnKQ==,type:str]
    version: 3.13.3
