apiVersion: v1
kind: Secret
metadata:
    name: cnpg-backup-s3-credentials
    namespace: nextcloud
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:1H4QPNvfOt4RSZVRfvky9qSyPgs=,iv:Hg1MJfLxvhV0cTKf2eif/UqFsuLxkfroFI67d+/j3mg=,tag:Q34KlO0SorbnGdKok4NAww==,type:str] #ENC[AES256_GCM,data:bQvYciRV9duSKIp9BnZOn6/duqP1hHVqmw==,iv:2xYKWtAASxNcwAdRQZHf6nTDbQORrTQ/QUbysk25bAw=,tag:qkB/8xoqPE4ThvJ6sCYsPA==,type:comment]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:jRBqMRmPFMV/bpWg58Rp6QVYXikbnH7Y6qCAS1JkZVWNmla2Rk/6CA==,iv:6URdb0K4iJiCG+bbuwGi7jtmQYFFZHx21+qFj/qtBo4=,tag:h2AV6Z4sL8Al4u4Oe5tmpQ==,type:str] #ENC[AES256_GCM,data:vFnODJNHW5JGTlLFFW79cnebQn7QskvzEw==,iv:fW6Ri65j+0TGd80iz1GEaa1EQO9+jEH51CRDfAZFUKU=,tag:l8KGFq+0J/Z1Vh4mFWsQbw==,type:comment]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFMGhyNmtIR3I3ZXZOVk5U
            b0FiM0gxQjRHVENHUVlBcEFPTTU1c1NqZUc4Ci93SEduOXBmTGtIOG5YT284RTMy
            WW1NYnJ2V3BCdTdUdlFqZXFhN3pDSU0KLS0tIEh3R3hvMGt0TmVXSkZlUVQrb205
            UUp3ZFF4Y1pqeGQ3NE41R2d0UStZdlkKsMGDCwm6dANSvCamkBbpL5CMLxXUEe07
            sGZhxa2HNACD4+sKxxuVtwHPoq1tjnNoS89QgYx/xv5BeOhRKe4jPA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l8urdgwakvjweqwxuzma2k3lnz0rym2juyjn9uls330keufsqc7s65c5j5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-11T01:53:45Z"
    mac: ENC[AES256_GCM,data:rPc68I4WeQqmZ8y5Lvqh/a7RmUbgWl99u/9NqhkVo1J9yhMvwlXhXnpOEUgsaNvOfheZYnSV6Jq2XZWdoR4Sz6nZyo8RZ8wEvfImLbzxWbl8svwClrGVw6QuX+uFAjfwUD3cJQT9Ezv8RW6ckh0PNXJl0pghTJc6/PjNJsK3ApA=,iv:PXfo3SLSTzci6UyQkYo2+StX34FHvn+SWynxOu3scp4=,tag:pW1NAQvdFHXxp0FU1zxWjg==,type:str]
    version: 3.13.3
