apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: valkey
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: "9.1.2"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: valkey
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: valkey
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: valkey
      automountServiceAccountToken: false
      containers:
        - name: main
          image: {{ .Values.image | quote }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          livenessProbe:
            exec:
              command: ["sh", "-c", "valkey-cli ping | grep PONG"]
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command: ["sh", "-c", "valkey-cli ping | grep PONG"]
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          startupProbe:
            exec:
              command: ["sh", "-c", "valkey-cli ping | grep PONG"]
            periodSeconds: 10
            failureThreshold: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: valkey-data
          {{- else }}
          emptyDir: {}
          {{- end }}
