apiVersion: v1
kind: ServiceAccount
metadata:
  name: valkey
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: valkey
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
